#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "Libs/File.h"
#include "Libs/xorstr.hpp"
#include "Libs/StringUtils.h"
#include "Libs/Json.hpp"
#include "Libs/Math/Math.h"
#include "../../Milky/Logger/Logger.h"
#include <d3d11.h>
#include <d3d12.h>
#include <dxgi.h>
#include "ImGui/imgui.h"
#include "ImGui/imgui_impl_dx11.h"
#include "ImGui/imgui_impl_dx12.h"
#include "ImGui/imgui_impl_win32.h"
#include "Colors/Color.h"
#include "../Milky/SDK/SDK.h"
#include <entt/entt.hpp>
#include "Kiero/Kiero.h"
#include "ImFX/imfx.h"
#include <d3d11.h>
#include <vector>
#include <sstream>
#include <stdio.h>
#include <string>
#include <cstring>
#include <iostream>
#include <algorithm>
#include <fmt/format.h>
#include "../../Milky/Utils/ImGuiUtils.h"
#pragma comment(lib, "d3d11.lib")