#pragma once
#include "Libs/File.h"
#include "Libs/xorstr.hpp"
#include "Libs/StringUtils.h"
#include "Libs/Json.hpp"
#include "Libs/Math/Math.h"
#include "../Milky/SDK/SDK.h"
#include <d3d11.h>
#include <dxgi.h>
#include "ImGui/imgui.h"
#include "Colors/Color.h"
#include <libhat.hpp>
#include "../Milky/SDK/SDK.h"